Resources:
  LambdaRole:
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Statement:
          - Action: [ 'sts:AssumeRole' ]
            Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: [ 'cloudwatch:PutMetricData' ]
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: emitMetrics
        - PolicyDocument:
            Statement:
              - Action: [ 'dynamodb:PutItem', 'dynamodb:GetItem', 'dynamodb:UpdateItem', 'dynamodb:BatchWriteItem', 'dynamodb:Query', 'dynamodb:DeleteItem', 'dynamodb:BatchDeleteItem' ]
                Effect: Allow
                Resource:
                  - { 'Fn::Sub': 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContentTable}' }
                  - { 'Fn::Sub': 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContentTable}/index/MarketplaceIdIndex' }
                  - { 'Fn::Sub': 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TargetingGroupsTable}' }
                  - { 'Fn::Sub': 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TargetingGroupsTable}/index/ContentIdIndex' }
            Version: '2012-10-17'
          PolicyName: connectToDynamo
    Type: AWS::IAM::Role

  APIGatewayExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [apigateway.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: ['lambda:Invoke*']
                Effect: Allow
                Resource:
                  Fn::GetAtt: [LambdaFunction, Arn]
            Version: '2012-10-17'
          PolicyName: apigInvokeLambda
    Type: AWS::IAM::Role
