Resources:
  LambdaFunction:
    Properties:
      CodeUri:
        Bucket: {'Fn::If': ['UseBatsKey', 'BATS::SAM::CodeS3Bucket', {"Fn::ImportValue": {Ref: 'DeploymentBucketImportName'}}]}
        Key: BATS::SAM::CodeS3Key
      Events:
        APIG:
          Properties:
            Method: ANY
            Path: /
            RestApiId: { Ref: LambdaAPIDefinition }
          Type: Api
      Handler: com.amazon.ata.advertising.service.LambdaMain::handleRequest
      MemorySize: 512
      Role:
        Fn::GetAtt: [ LambdaRole, Arn ]
      Runtime: java8
      Timeout: 900
    Type: AWS::Serverless::Function
