---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template configuring ATACurriculumAdvertisingServiceLambda in Lambda fronted by API Gateway
Outputs:
  StackArn:
    Description: Use this as the stack_arn in your cloud_formation_deployment_stack
      override.
    Value: {Ref: 'AWS::StackId'}
  ApiId:
    Description: The ApiId of your APIGateway RestAPI
    Value: {Ref: 'LambdaAPIDefinition'}
  ApiStage:
    Description: Your APIGateway stage
    Value: {Ref: 'LambdaAPIDefinitionStage'}
Parameters:
  Stage: {Type: String, Default: ''}
  UseBatsKeyParam: {Type: String, Default: 'false', AllowedValues: ['true','false']}
  DeploymentBucketImportName:
    Type: String
    Default: "DeploymentBucket"
Conditions:
  UseBatsKey:
    'Fn::Equals':
    - {Ref: UseBatsKeyParam}
    - 'true'
Resources:
  LambdaAPIDefinition:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: {Ref: Stage}
      DefinitionBody: REPLACE_WITH_SWAGGER_DEFINITION
  LambdaLogGroup:
    DependsOn: LambdaFunction
    Properties:
      LogGroupName: {"Fn::Sub": "/aws/lambda/${LambdaFunction}"} # Default lambda log group naming format
    Type: AWS::Logs::LogGroup
