---
Parameters:
  HydraTestResultsRoleImportName:
    Type: String
    Default: HydraTestResultsRole
  IsSAMToolkit:
    Type: String
    AllowedValues: ["true","false"]
    Default: "false"
Conditions:
  CreateHydraConfig:
    Fn::And:
      - {Condition: HasHydra}
      - Fn::Equals:
          - {"Ref": "IsSAMToolkit"}
          - "false"
Resources:
  HydraPersistentConfiguration:
    Type: "AWS::CodeTest::PersistentConfiguration"
    Condition: CreateHydraConfig
    Properties:
      Name: !Sub "${AWS::StackName}"
      ResultsRoleArn:
        "Fn::ImportValue":
          "Ref": "HydraTestResultsRoleImportName"
Outputs:
  PersistentConfigurationId:
    Condition: CreateHydraConfig
    Value: !Ref HydraPersistentConfiguration
